name: Code Check

on: [push, pull_request]

jobs:
  nextjs-lint:
    runs-on: ubuntu-latest
    name: npm lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  eslint-check:
    runs-on: ubuntu-latest
    name: npm run eslint:check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run eslint:check
        run: npm run eslint:check

  format-check:
    runs-on: ubuntu-latest
    name: npm run format:check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run format:check
        run: npm run format:check
